name: rTriggers
author: Reil
main: com.reil.bukkit.rTriggers.rTriggers
version: 2.7.4a
database: true
softdepend: [Permissions, PermissionsEx, Register]
commands:
    rtriggers:
        description: The catch-all command. Used to reload, really.
        usage: rtriggers [option]
        permission: rtriggers.admin
        permission-message: You don't have permission for that!